# Generated by Django 4.1 on 2022-11-14 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=3, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='entryitem',
            old_name='amount',
            new_name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='entryitem',
            name='is_debit',
        ),
        migrations.RemoveField(
            model_name='entryitem',
            name='label',
        ),
        migrations.RemoveField(
            model_name='entryitem',
            name='type',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='balance_type',
            field=models.CharField(choices=[('D', 'مدين'), ('C', 'دائن')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounttype',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='level_type',
            field=models.CharField(choices=[('M', 'رئيسي'), ('S', 'فرعي')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounttype',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_account', to='main.accounttype'),
        ),
        migrations.AddField(
            model_name='entryitem',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_items', to='main.accounttype'),
        ),
        migrations.AddField(
            model_name='entryitem',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_items', to='main.accounttype'),
        ),
        migrations.AddField(
            model_name='entryitem',
            name='debit_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entryitem',
            name='exchange_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entryitem',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='main.accountingentry'),
        ),
        migrations.AlterField(
            model_name='entryitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='main.project'),
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='accounts', to='main.currency'),
        ),
    ]
