# Generated by Django 4.1 on 2022-12-07 10:23

from django.db import migrations


def rename_permissions(apps, schema_editor):
    # We can't import the Group & Permission model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    permission_model = apps.get_model('auth', 'Permission')
    content_type = apps.get_model('contenttypes', 'ContentType')
    group_perms = content_type.objects.filter(app_label="auth", model="group")\
        .first().permission_set
    permission_perms = content_type.objects.filter(app_label="auth", model="permission")\
        .first().permission_set

    for g_perm in group_perms.all():
        g_perm.delete()

    for p_perm in permission_perms.all():
        p_perm.delete()

    group_perms_objs = [
        permission_model(
            name="إضافة مجموعة", codename="add_group"
        ),
        permission_model(
            name="تغيير بيانات مجموعة", codename="change_group"
        ),
        permission_model(
            name="حذف مجموعة", codename="delete_group"
        ),
        permission_model(
            name="عرض بيانات مجموعة", codename="view_group"
        ),
    ]

    permission_perms_objs = [
        permission_model(
            name="إضافة صلاحية", codename="add_permission"
        ),
        permission_model(
            name="تغيير بيانات صلاحية", codename="change_permission"
        ),
        permission_model(
            name="حذف صلاحية", codename="delete_permission"
        ),
        permission_model(
            name="عرض بيانات صلاحية", codename="view_permission"
        ),
    ]

    group_perms.set(group_perms_objs, clear=True, bulk=False)

    permission_perms.set(permission_perms_objs, clear=True, bulk=False)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_options_user_is_reset_password_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_permissions)
    ]
